version: '3'
services:
  segmed-api:
    container_name: segmed-api
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - segmed-mysql-db
    networks:
      - segmed-network
  segmed-mysql-db:
    image: mysql:5.7
    container_name: segmed-mysql-db
    ports:
      - 3308:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - segmed-network
volumes:
  api:
  database_mysql:

networks:
  segmed-network:
    driver: bridge